##############################
# FastCGI 缓存绕过条件
map $cookie_nocache $fastcgi_skip_cookie {
    default 1;
    ''      0;
    '0'     0;
}

map "$arg_nocache$arg_comment" $fastcgi_skip_args {
    default 1;
    ''      0;
    '0'     0;
}

map $http_pragma $fastcgi_skip_pragma {
    default 1;
    ''      0;
    '0'     0;
}

map $http_authorization $fastcgi_skip_authorization {
    default 1;
    ''      0;
    '0'     0;
}

map $http_cache_control $fastcgi_skip_cache_control {
    default                                                     0;
    ~*(?:^|,)\s*(?:no-cache|no-store|max-age\s*=\s*0)\s*(?:,|$) 1;
}

map "$fastcgi_skip_cookie$fastcgi_skip_args$fastcgi_skip_pragma$fastcgi_skip_authorization$fastcgi_skip_cache_control" $fastcgi_skip_cache {
    default 0;
    ~1      1;
}
