# /etc/nginx/conf.d/default.conf
# default.conf 与 nginx 复用
server {
    listen 80 reuseport default_server;
    listen [::]:80 reuseport default_server;
    server_name _;

    return 444;

    # https://mailman.nginx.org/pipermail/nginx-devel/2018-September/011458.html
    # https://trac.nginx.org/nginx/ticket/1756
    error_page 400 405 414 494 501 505 = /close_conn;
    location = /close_conn {
        internal;
        return 444;
    }
}

server {
    listen 443 ssl reuseport default_server;
    listen [::]:443 ssl reuseport default_server;
    listen 443 quic reuseport default_server;
    listen [::]:443 quic reuseport default_server;
    server_name _;

    ssl_reject_handshake on; # 该指令出现在 1.19.4 版本中.
    ssl_certificate /etc/nginx/certs/default_server.crt;
    ssl_certificate_key /etc/nginx/certs/default_server.key;
    ssl_stapling off;
    ssl_stapling_verify off;

    return 444;

    # 400: 异常或无法解析的 HTTP 请求
    # 405: 不支持的 HTTP 方法
    # 414: 请求行或 URI 过长
    # 421: HTTP/2 连接被复用于不匹配的虚拟主机
    # 494: 请求头/Cookie 超过缓冲区
    # 497: HTTPS 端口收到明文 HTTP
    # 501: 不支持的 Transfer-Encoding 等未实现能力
    # 505: HTTP 版本不支持
    error_page 400 405 414 421 494 497 501 505 = /close_conn;
    location = /close_conn {
        internal;
        return 444;
    }
}

##############################
# 信任内网 IP 地址范围
# https://www.rfc-editor.org/info/rfc1918
set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.16.0.0/12;
set_real_ip_from 192.168.0.0/16;

# https://www.rfc-editor.org/info/rfc4193
set_real_ip_from fc00::/7;

##############################
# CloudFlare IP 地址范围
# https://www.cloudflare.com/zh-cn/ips
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 104.16.0.0/13;
set_real_ip_from 104.24.0.0/14;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;

set_real_ip_from 2400:cb00::/32;
set_real_ip_from 2606:4700::/32;
set_real_ip_from 2803:f800::/32;
set_real_ip_from 2405:b500::/32;
set_real_ip_from 2405:8100::/32;
set_real_ip_from 2a06:98c0::/29;
set_real_ip_from 2c0f:f248::/32;

##############################
# 使用 CF-Connecting-IP 来获取 Cloudflare 客户端的真实 IP
real_ip_header CF-Connecting-IP;
# 递归查找真实 IP
real_ip_recursive on;
