server {
    listen       80;
    listen       [::]:80;
    server_name  honeok.com www.honeok.com;
    return 301   https://www.honeok.com$request_uri;
}

server {
    listen       443 ssl;
    listen       [::]:443 ssl;
    listen       443 quic;
    listen       [::]:443 quic;
    server_name  honeok.com;

    ssl_certificate      /etc/nginx/certs/honeok.com_fullchain.pem;
    ssl_certificate_key  /etc/nginx/certs/honeok.com_key.pem;

    return 301   https://www.honeok.com$request_uri;
}

server {
    listen       443 ssl;
    listen       [::]:443 ssl;
    listen       443 quic;
    listen       [::]:443 quic;
    server_name  www.honeok.com;

    ssl_certificate      /etc/nginx/certs/honeok.com_fullchain.pem;
    ssl_certificate_key  /etc/nginx/certs/honeok.com_key.pem;

    resolver 8.8.8.8 1.1.1.1 valid=30s ipv6=off;
    resolver_timeout 5s;

    client_max_body_size 12k;

    more_set_headers 'Alt-Svc: h3=":443"; ma=86400,h3-29=":443"; ma=86400';

    # 访问控制
    access_by_lua_file /etc/nginx/lua/access/entry.lua;

    location / {
        proxy_pass         http://127.0.0.1:6969;
        proxy_http_version 1.1;

        # WebSocket 支持
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection $connection_upgrade;

        # 客户端信息透传
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;

        early_hints        $early_hints; # HTTP 103 Early Hints: 透传上游返回的 103, 让浏览器提前预加载资源

        # 上游有缓存头就遵循, 上游没缓存头才按静态资源后缀兜底
        header_filter_by_lua_file /etc/nginx/lua/header_filter/static_cache_control.lua;
    }

##############################
# internal html.
    error_page 403 /403.html;
    location = /403.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }
}
