server {
    listen       80;
    listen       [::]:80;
    server_name  imgapi.honeok.com;
    return 301   https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen       [::]:443 ssl;
    listen       443 quic;
    listen       [::]:443 quic;
    server_name  imgapi.honeok.com;

    ssl_certificate      /etc/nginx/certs/honeok.com_fullchain.pem;
    ssl_certificate_key  /etc/nginx/certs/honeok.com_key.pem;

    client_max_body_size 1m;
    more_set_headers 'Alt-Svc: h3=":443"; ma=86400,h3-29=":443"; ma=86400';

    # 访问控制
    access_by_lua_file /etc/nginx/lua/access/entry.lua;

##############################
    location = / {
        default_type text/plain;
        return 200 "ok\n";
    }

    # 健康检查
    location = /health {
        default_type application/json;
        return 200 '{"status":"ok","time":"$time_iso8601"}\n';
        access_log off;
    }

    location = /favicon.ico {
        return 301 https://fastly.jsdelivr.net/gh/vscode-icons/vscode-icons@master/icons/file_type_image.svg;
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        root /usr/local/openresty/nginx/html;
        allow all;
        log_not_found off;
        access_log off;
    }

##############################
# 随机黑丝 API
    location = /api/silk {
        rewrite ^ /api/silk/ last;
    }

    location /api/silk/ {
        alias /usr/local/openresty/nginx/html/imgapi/silk/;
        random_index on;
        autoindex off; # 禁止显示目录列表

        # 禁用浏览器缓存
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        add_header X-Content-Type-Options "nosniff" always;
    }

##############################
# 国旗 Icons 4x3
    location ^~ /api/flag-icons/4x3/ {
        alias /usr/local/openresty/nginx/html/imgapi/flag-icons/4x3/;
        autoindex off;

        types {
            image/svg+xml svg;
        }
        default_type image/svg+xml;

        add_header Cache-Control "public, max-age=86400" always;
        add_header X-Content-Type-Options "nosniff" always; # 告诉浏览器 不要自己猜文件类型 必须按照服务器返回的 Content-Type 来处理
    }

# 国旗 Icons 1x1
    location ^~ /api/flag-icons/1x1/ {
        alias /usr/local/openresty/nginx/html/imgapi/flag-icons/1x1/;
        autoindex off;

        types {
            image/svg+xml svg;
        }
        default_type image/svg+xml;

        add_header Cache-Control "public, max-age=86400" always;
        add_header X-Content-Type-Options "nosniff" always;
    }

##############################
# Mihomo icons svg
    location ^~ /api/mihomo/icons/svg/ {
        alias /usr/local/openresty/nginx/html/imgapi/mihomo/icons/svg/;
        autoindex off;

        types {
            image/svg+xml svg;
        }
        default_type image/svg+xml;

        add_header Cache-Control "public, max-age=86400" always;
        add_header X-Content-Type-Options "nosniff" always;
    }

# Mihomo icons png
    location ^~ /api/mihomo/icons/png/ {
        alias /usr/local/openresty/nginx/html/imgapi/mihomo/icons/png/;
        autoindex off;

        types {
            image/png png;
        }
        default_type image/png;

        add_header Cache-Control "public, max-age=86400" always;
        add_header X-Content-Type-Options "nosniff" always;
    }

##############################
# internal html.
    error_page 403 /403.html;
    location = /403.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }
}
