server {
    listen       80;
    listen       [::]:80;
    server_name  imgapi.honeok.com;
    return 301   https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen       [::]:443 ssl;
    listen       443 quic;
    listen       [::]:443 quic;
    server_name  imgapi.honeok.com;

    ssl_certificate      /etc/nginx/certs/honeok.com_fullchain.pem;
    ssl_certificate_key  /etc/nginx/certs/honeok.com_key.pem;

    resolver 8.8.8.8 1.1.1.1 valid=30s ipv6=off;
    resolver_timeout 5s;

    client_max_body_size 5m;
    more_set_headers 'Alt-Svc: h3=":443"; ma=86400';

    # 访问控制
    access_by_lua_file /etc/nginx/lua/access/entry.lua;

##############################
    location = / {
        default_type text/plain;
        content_by_lua_block {
            ngx.say("ok")
        }
    }

    # 健康检查
    location = /health {
        default_type application/json;
        content_by_lua_block {
            ngx.say('{"status":"ok","time":"' .. ngx.var.time_iso8601 .. '"}')
        }
        access_log off;
    }

    location = /favicon.ico {
        return 301 https://fastly.jsdelivr.net/gh/vscode-icons/vscode-icons@master/icons/file_type_image.svg;
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        root /usr/local/openresty/nginx/html;
        allow all;
        log_not_found off;
        access_log off;
    }

    location ~* \.php {
        return 444;
    }

##############################
# 随机黑丝 API
    location = /api/silk {
        rewrite_by_lua_block {
            return ngx.exec("/api/silk/")
        }
    }

    location /api/silk/ {
        alias /usr/local/openresty/nginx/html/imgapi/silk/;
        random_index on;
        autoindex off; # 禁止显示目录列表

        more_set_headers 'Cache-Control: no-store'; # 禁用浏览器缓存
    }

##############################
# 国旗 Icons
    location ^~ /api/flag-icons/ {
        types {
            image/svg+xml svg;
        }
        default_type image/svg+xml;

        rewrite_by_lua_block {
            local uri = ngx.var.uri
            local match = ngx.re.match(uri, [[^/api/flag-icons/(1x1|4x3)/([a-z0-9_-]+\.svg)$]], "ijo")
            if not match then
                return ngx.exit(404)
            end
        }

        alias /usr/local/openresty/nginx/html/imgapi/flag-icons/;
        autoindex off; # 禁止显示目录列表

        more_set_headers 'Cache-Control: public, max-age=2592000';
    }

##############################
# Mihomo Icons
    location ^~ /api/mihomo/icons/ {
        types {
            image/svg+xml svg;
            image/png png;
        }

        rewrite_by_lua_block {
            local uri = ngx.var.uri
            local match = ngx.re.match(uri, [[^/api/mihomo/icons/(svg|png)/([a-zA-Z0-9_.-]+\.(?:svg|png))$]], "ijo")
            if not match then
                return ngx.exit(404)
            end
        }

        alias /usr/local/openresty/nginx/html/imgapi/mihomo/icons/;
        autoindex off; # 禁止显示目录列表

        more_set_headers 'Cache-Control: public, max-age=2592000';
    }

##############################
# internal html.
    error_page 403 /403.html;
    location = /403.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }
}
