upstream rsshub {
    hash $request_uri consistent; # URL 哈希, consistent: 让哈希分配在节点增删时更稳定
    keepalive 64;
    keepalive_timeout 60s;
    keepalive_requests 1000;

    # https://www.1itao.com/rsshub.html
    # 在 30 秒窗口内, 如果这个后端失败达到 2 次, Nginx 认为它临时不可用
    server 86.38.200.13:1200 max_fails=2 fail_timeout=30s weight=100; # Los Angeles
    server 97.64.36.218:8880 max_fails=2 fail_timeout=30s weight=100; # Los Angeles
    server 107.173.39.67:40002 max_fails=2 fail_timeout=30s weight=100; # Los Angeles
    server 74.211.110.28:1200 max_fails=2 fail_timeout=30s weight=100; # Los Angeles
    server 144.202.100.72:1200 max_fails=2 fail_timeout=30s weight=100; # Santa Clara
    server 107.173.181.24:1200 max_fails=2 fail_timeout=30s weight=95; # Seattle
    server 38.182.100.178:1200 max_fails=2 fail_timeout=30s weight=85; # Salt Lake City
    server 64.181.210.93:1200 max_fails=2 fail_timeout=30s weight=80; # Chicago
    server 172.245.82.46:1200 max_fails=2 fail_timeout=30s weight=80; # Elk Grove Village
    server 192.210.226.242:1234 max_fails=2 fail_timeout=30s weight=80; # New York
}

server {
    listen       80;
    listen       [::]:80;
    server_name  rsshub.honeok.com;
    return 301   https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen       [::]:443 ssl;
    listen       443 quic;
    listen       [::]:443 quic;
    server_name  rsshub.honeok.com;

    ssl_certificate      /etc/nginx/certs/honeok.com_fullchain.pem;
    ssl_certificate_key  /etc/nginx/certs/honeok.com_key.pem;

    more_set_headers 'Alt-Svc: h3=":443"; ma=86400,h3-29=":443"; ma=86400';

    # 访问控制
    access_by_lua_file /etc/nginx/lua/access/entry.lua;

    location / {
        proxy_pass         http://rsshub;

        proxy_http_version 1.1;
        proxy_set_header   Connection "";

        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host $host;

        early_hints        $early_hints; # HTTP 103 Early Hints: 透传上游返回的 103, 让浏览器提前预加载资源

        proxy_connect_timeout 5s; # 连接某个 RSSHub 节点超过 5 秒就放弃
        proxy_send_timeout 30s;
        proxy_read_timeout 120s; # 有些路由比较慢 给它最多 120 秒返回

        # 如果当前节点挂了 超时 返回 500/502/503/504 就尝试下一个节点
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;

        proxy_next_upstream_tries 3; # 最多尝试 3 个节点
        proxy_next_upstream_timeout 40s; # 整个故障转移最多等待 40 秒

        # 让 Nginx 接管上游错误页面
        proxy_intercept_errors on;
    }

##############################
# internal html.
    error_page 403 /403.html;
    location = /403.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/local/openresty/nginx/html;
        internal;
    }
}
