# https://github.com/apache/apisix/blob/3.18.0/conf/config.yaml.example
# https://github.com/apache/apisix/blob/3.18.0/apisix/cli/config.lua

---
apisix:
  node_listen: 9080 # APISIX HTTP 请求监听端口
  enable_admin: true # Admin API
  enable_dev_mode: false # 开发模式, 启用后将 Nginx worker_processes 设置为 1
  enable_reuseport: true # 启用 SO_REUSEPORT, 允许多个 Nginx worker 复用监听端口
  show_upstream_status_in_response_header: false # 控制是否在响应头中返回上游状态码, false 时仅上游返回 5xx 才返回 X-APISIX-Upstream-Status

  enable_ipv6: true
  enable_http2: true

  # proxy_protocol:
  #   listen_http_port: 9181 # 接收携带 PROXY Protocol 的 HTTP 请求监听端口
  #   listen_https_port: 9182 # 接收携带 PROXY Protocol 的 HTTPS 请求监听端口
  #   enable_tcp_pp: true # 是否在所有 TCP stream 监听端口接收 PROXY Protocol
  #   enable_tcp_pp_to_upstream: true # 是否向所有 TCP stream 上游发送 PROXY Protocol

  enable_server_tokens: false # 是否在 Server 响应头中显示 APISIX 版本
  extra_lua_path: "" # 扩展 Lua 模块搜索路径, 仅加载自定义 Lua 代码时配置
  extra_lua_cpath: "" # 扩展 Lua C 模块搜索路径, 仅加载自定义动态库时配置
  # lua_module_hook: "my_project.my_hook" # 加载自定义 Lua Hook 模块, 仅需要修改 APISIX 内部行为时配置

  # 代理缓存配置
  proxy_cache:
    cache_ttl: 10s # 上游未指定缓存时间时的默认磁盘缓存 TTL
    zones:
      - name: disk_cache # 磁盘缓存区域
        memory_size: 50m # 缓存索引共享内存大小
        disk_size: 1G # 磁盘缓存空间上限
        disk_path: /tmp/disk_cache # 磁盘缓存目录
        cache_levels: "1:2" # 缓存目录层级
      - name: memory_cache # 内存缓存区域
        memory_size: 50m # 内存缓存大小

  delete_uri_tail_slash: false # 是否删除 URI 末尾的 /
  normalize_uri_like_servlet: false # 是否按 Java Servlet/Tomcat 规则规范化 URI
  match_uri_encoded_slash: false # 是否在路由匹配时保留 URL 编码的斜杠 %2F

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

# deployment:
#   role: traditional
#   role_traditional:
#     config_provider: etcd
#   etcd:
#     host:
#       - http://127.0.0.1:2379
#
# To configure via environment variables, you can use `${{VAR}}` syntax. For instance:
#
# deployment:
#   role: traditional
#   role_traditional:
#     config_provider: etcd
#   etcd:
#     host:
#       - http://${{ETCD_HOST}}:2379
#
# And then run `export ETCD_HOST=$your_host` before `make init`.
#
# If the configured environment variable can't be found, an error will be thrown.
#
# Also, If you want to use default value when the environment variable not set,
# Use `${{VAR:=default_value}}` instead. For instance:
#
# deployment:
#   role: traditional
#   role_traditional:
#     config_provider: etcd
#   etcd:
#     host:
#       - http://${{ETCD_HOST:=localhost}}:2379
#
# This will find environment variable `ETCD_HOST` first, and if it's not exist it will use `localhost` as default value.

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key:
      - name: admin
        key: "" # using fixed API token has security risk, please update it when you deploy to production environment. If passed empty then will be autogenerated by APISIX and will be written back here. Recommended is to use external mechanism to generate and store the token.
        role: admin
