# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2026 honeok <i@honeok.com>

# References:
# https://cn.angie.software/angie/docs/installation
# https://github.com/nginx/docker-nginx

# / # angie -V
# Angie version: Angie/1.12.1
# nginx version: nginx/1.31.2
# built on Fri, 17 Jul 2026 07:01:39 GMT
# built with OpenSSL 3.5.7 9 Jun 2026
# TLS SNI support enabled
# configure arguments: --prefix=/etc/angie --conf-path=/etc/angie/angie.conf --error-log-path=/var/log/angie/error.log \
    # --http-log-path=/var/log/angie/access.log --lock-path=/run/angie.lock --modules-path=/usr/lib/angie/modules --pid-path=/run/angie.pid \
    # --sbin-path=/usr/sbin/angie --http-acme-client-path=/var/lib/angie/acme --http-client-body-temp-path=/var/cache/angie/client_temp \
    # --http-fastcgi-temp-path=/var/cache/angie/fastcgi_temp --http-proxy-temp-path=/var/cache/angie/proxy_temp \
    # --http-scgi-temp-path=/var/cache/angie/scgi_temp --http-uwsgi-temp-path=/var/cache/angie/uwsgi_temp \
    # --user=angie --group=angie --with-file-aio --with-http_acme_module --with-http_addition_module --with-http_auth_request_module \
    # --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module \
    # --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module \
    # --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_v3_module --with-mail --with-mail_ssl_module \
    # --with-stream --with-stream_acme_module --with-stream_mqtt_preread_module --with-stream_rdp_preread_module --with-stream_realip_module \
    # --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --feature-cache=../angie-feature-cache \
    # --with-ld-opt='-Wl,--as-needed,-O1,--sort-common -Wl,-z,pack-relative-relocs'

# https://cn.angie.software/angie/docs/installation/oss_packages
FROM alpine:3.23.5@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40 AS base

FROM base AS dist

## angie
ARG ANGIE_VERSION=1.12.1
ENV ANGIE_VERSION $ANGIE_VERSION

RUN set -ex \
    && addgroup -g 101 -S angie \
    && adduser -S -D -H -u 101 -h /var/cache/angie -s /sbin/nologin -G angie -g angie angie \
    && apk add --no-cache \
        curl \
        ca-certificates \
        gettext-envsubst \
        tzdata \
# download the public key of the Angie repo for package verification.
    && curl -fsSL https://angie.software/keys/angie-signing.rsa -o /etc/apk/keys/angie-signing.rsa \
    && angiePackages=angie=$( \
        apk query --no-cache --from none --all-matches \
            --repository "@angie https://download.angie.software/angie/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" \
            --fields version angie \
            | sed -n "s/^Version: \($ANGIE_VERSION-r[0-9][0-9]*\)$/\1/p" | sort -V | tail -n 1 \
    ) \
# we need to make sure angie.software packages are pulled in, which isnt guaranteed
# as Alpine repos might have the same version in the repos.
# query angie.software binaries for the dependencies
    && angieDeps=$(apk query --summarize depends --recursive --no-cache \
            --repository "@angie https://download.angie.software/angie/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" \
            ${angiePackages/=/@angie=}) \
# install those dependencies from alpine repos
            && apk add --no-cache $angieDeps \
# limit apk to angie.software repos only to install the requested packages
    && apk add --repositories-file /dev/null -X "https://download.angie.software/angie/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" --no-cache $angiePackages
