---
name: "Build test angie"

on:
  push:
    paths:
      - "lnmp/angie/**"
      - "!lnmp/angie/**/*.md"
  pull_request:
    paths:
      - "lnmp/angie/**"
      - "!lnmp/angie/**/*.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  WORK_DIR: lnmp/angie

jobs:
  build:
    name: "Build ${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, platform: linux/amd64, arch: amd64 }
          - { os: ubuntu-24.04-arm, platform: linux/arm64, arch: arm64 }
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Configure and build angie"
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: ${{ env.WORK_DIR }}
        run: |
          set -euxo pipefail

          ANGIE_VERSION=$(gh api --paginate repos/webserver-llc/angie/tags --jq '.[].name' | sed -n 's/^Angie-//p' | sort -V | tail -n 1)
          NGX_GEOIP2_VERSION=$(gh api --paginate repos/leev/ngx_http_geoip2_module/tags --jq '.[].name' | sort -V | tail -n 1)
          HEADERS_MORE_VERSION=$(gh api --paginate repos/openresty/headers-more-nginx-module/tags --jq '.[].name | sub("^v"; "")' | sort -V | tail -n 1)
          NGX_ZSTD_VERSION=$(gh api repos/facebook/zstd/releases/latest --jq '.tag_name | sub("^v"; "")')

          docker build \
            --no-cache \
            --progress=plain \
            --platform ${{ matrix.platform }} \
            --build-arg ANGIE_VERSION=$ANGIE_VERSION \
            --build-arg NGX_GEOIP2_VERSION=$NGX_GEOIP2_VERSION \
            --build-arg HEADERS_MORE_VERSION=$HEADERS_MORE_VERSION \
            --build-arg NGX_ZSTD_VERSION=$NGX_ZSTD_VERSION \
            --tag $GITHUB_REPOSITORY_OWNER/angie:$ANGIE_VERSION-${{ matrix.arch }} \
            . 2>&1 | tee build.log

          docker run --rm \
            --entrypoint angie \
            $GITHUB_REPOSITORY_OWNER/angie:$ANGIE_VERSION-${{ matrix.arch }} \
            -V
